In [ ]:
#Task 2:Exploratory Data Analysis (EDA)

In [ ]:
import pandas as pd

df = pd.read_csv("books_dataset.csv")

df.head()

                                   Title    Price Availability Rating
0                   A Light in the Attic  Â£51.77     In stock  Three
1                     Tipping the Velvet  Â£53.74     In stock    One
2                             Soumission  Â£50.10     In stock    One
3                          Sharp Objects  Â£47.82     In stock   Four
4  Sapiens: A Brief History of Humankind  Â£54.23     In stock   Five

In [ ]:
print("Rows and columns:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nDataset information:")
df.info()

print("\nStatistical summary:")
df.describe(include="all")

Rows and columns: (100, 4)

Column names:
['Title', 'Price', 'Availability', 'Rating']

Data types:
Title           object
Price           object
Availability    object
Rating          object
dtype: object

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         100 non-null    object
 1   Price         100 non-null    object
 2   Availability  100 non-null    object
 3   Rating        100 non-null    object
dtypes: object(4)
memory usage: 3.3+ KB

Statistical summary:

                       Title    Price Availability Rating
count                    100      100          100    100
unique                   100       99            1      5
top     A Light in the Attic  Â£44.18     In stock  Three
freq                       1        2          100     22

In [ ]:
print("Missing values:")
print(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())

print("Unique titles:", df["Title"].nunique())

print("Availability values:")
print(df["Availability"].value_counts())

Missing values:
Title           0
Price           0
Availability    0
Rating          0
dtype: int64
Duplicate rows: 0
Unique titles: 100
Availability values:
Availability
In stock    100
Name: count, dtype: int64

In [11]:
df["Price"] = (
    df["Price"]
    .astype(str)
    .str.replace("£", "", regex=False)
    .str.replace("Â", "", regex=False)
)

df["Price"] = pd.to_numeric(
    df["Price"], errors="coerce"
)

rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["Rating"] = df["Rating"].map(rating_map)

df = df.drop_duplicates()

print(df.dtypes)
df.head()

Title            object
Price           float64
Availability     object
Rating            int64
dtype: object

                                   Title  Price Availability  Rating
0                   A Light in the Attic  51.77     In stock       3
1                     Tipping the Velvet  53.74     In stock       1
2                             Soumission  50.10     In stock       1
3                          Sharp Objects  47.82     In stock       4
4  Sapiens: A Brief History of Humankind  54.23     In stock       5

In [12]:
print("Average price:", df["Price"].mean())
print("Median price:", df["Price"].median())
print("Minimum price:", df["Price"].min())
print("Maximum price:", df["Price"].max())

print("\nBooks by rating:")
print(df["Rating"].value_counts().sort_index())

print("\nAverage price by rating:")
print(df.groupby("Rating")["Price"].mean())

Average price: 34.560700000000004
Median price: 34.775000000000006
Minimum price: 10.16
Maximum price: 58.11

Books by rating:
Rating
1    22
2    19
3    22
4    18
5    19
Name: count, dtype: int64

Average price by rating:
Rating
1    35.519545
2    35.909474
3    36.839091
4    33.981667
5    30.012105
Name: Price, dtype: float64

In [13]:
q1 = df["Price"].quantile(0.25)
q3 = df["Price"].quantile(0.75)

iqr = q3 - q1

lower_limit = q1 - 1.5 * iqr
upper_limit = q3 + 1.5 * iqr

outliers = df[
    (df["Price"] < lower_limit) |
    (df["Price"] > upper_limit)
]

print(outliers[["Title", "Price"]])

Empty DataFrame
Columns: [Title, Price]
Index: []